'use strict';
// Source-grounded editorial content. This is local documentation, not an AI or support service.
window.STUDIO_HELP = [
 {id:'create',category:'create',title:'Create a project and choose its canvas',platform:'iOS / Android',terms:'new animation project presets dimensions fps setup',steps:['Open Studio and go to the project library. Enter a project name in the New Animation or New animation card.','Choose a canvas preset and FPS, then Create. Canvas dimensions describe pixels; FPS controls the speed of timeline ticks.','On iOS, Project Settings can change name, dimensions and FPS. Canvas resizing crops or extends the viewport without scaling existing artwork. Android currently chooses these settings at creation.'],note:'A project is stored locally. Creating one here on the website is not supported.'},
 {id:'drawing',category:'create',title:'Draw on an editable layer',platform:'iOS / Android',terms:'pencil brush pen color size stroke tool toolbar',steps:['Open a project and select a visible, unlocked layer.','Choose a drawing tool from the Studio toolbar. Open its settings to choose available size and color controls.','Draw on the canvas. Use Undo for the last committed edit and Redo to restore it.'],note:'iOS has a broader tool set. The Android foundation currently provides a round pencil and layer-local eraser; advanced brush parity is still pending.'},
 {id:'layers',category:'create',title:'Find a hidden or locked drawing',platform:'iOS / Android',terms:'invisible missing lock opacity stack order show hide',steps:['Open Layers and select the layer you want to edit.','Check visibility and opacity. A hidden layer or zero opacity makes its content invisible.','Unlock a layer before changing its artwork. Check stack order when another layer covers it.'],note:'Do not delete a project to recover hidden content. Android layer opacity, visibility and order apply across its frames.'},
 {id:'erase',category:'create',title:'Erase without clearing other layers',platform:'iOS / Android',terms:'eraser clear delete remove strokes',steps:['Select the intended drawing layer and confirm it is visible and unlocked.','Choose Eraser and inspect its settings before drawing over the marks.','Use Undo if you erase too much.'],note:'The Android eraser clears marks inside the active layer, revealing lower layers and the white canvas background. It is not an imported-photo background remover. iOS offers additional eraser controls; availability depends on the selected target.'},
 {id:'timing',category:'animate',title:'Change a frame’s exposure',platform:'iOS / Android',terms:'hold duration fps playback timeline speed frames',steps:['Select the frame in the timeline.','Open the frame exposure control and choose the hold in ticks.','Preview playback. A frame held for 3 ticks at 12 FPS lasts 3/12 of a second.'],note:'Changing project FPS changes tick speed. On iOS, saved audio timing remains absolute; retiming frames does not automatically stretch audio.'},
 {id:'frames',category:'animate',title:'Add, duplicate or remove a frame',platform:'iOS / Android',terms:'timeline copy pose delete last frame undo',steps:['Select the frame next to where you want to work.','Use Add frame for a blank frame, or Duplicate to start with the selected pose.','Delete removes the selected frame, not the whole project. Keep at least one frame and use Undo to restore a removal.'],note:'A layer lock can prevent destructive operations on its content. Android’s duplicate action creates separate editable frame and stroke identities.'},
 {id:'guides',category:'animate',title:'Use onion skin and the grid in iOS Studio',platform:'iOS',terms:'previous next frame overlay guides onion grid alignment',steps:['Open the relevant Studio canvas or onion-skin settings.','Enable onion skin to compare neighboring frames, then adjust the exposed settings for your scene.','Use grid settings for alignment. Revisit the controls to hide guides when they are distracting.'],note:'These are editor guides, not additional drawing layers. Android guide controls are not part of the current foundation.'},
 {id:'saving',category:'keep',title:'Save and return to the project library',platform:'iOS / Android',terms:'back projects persist reopen autosave unsaved storage failed',steps:['Finish the current edit and use Save when available.','Use the Studio back or Projects control to return to the library. If saving reports an error, keep the editor open and read the message.','Select the project in the library to continue editing.'],note:'A save error is not success. Local data can be lost when the app is uninstalled. Android currently has no editable-project backup or cross-platform importer; PNG exports only preserve rendered pictures.'},
 {id:'export',category:'keep',title:'Choose an export that fits your result',platform:'iOS',terms:'png sequence mp4 movie gif sound transparent share files',steps:['Open Studio’s export controls and choose an available format.','PNG sequence exports pictures without sound. MP4 uses a white background and saved project audio as stereo AAC. GIF uses reduced colors, a white background and no audio.','Complete the export, then use the system sharing or Files flow to place the result.'],note:'Official channel publishing remains unfinished. Exporting a rendered result is different from saving an editable project.'},
 {id:'android',category:'keep',title:'Export Android PNGs with frame timing',platform:'Android foundation',terms:'zip sequence manifest png document picker export cancel limit',steps:['Stop playback and choose Export. Select Current frame PNG or PNG sequence ZIP.','The app captures the current project revision, including unsaved edits, and prepares the output. Choose a destination in Android’s document picker.','The ZIP includes one PNG per frame and manifest.json with FPS, startTick and holdTicks. Each tick lasts exactly 1/FPS seconds.'],note:'Current source limits export to 4 megapixels per canvas and 256 MiB total. It exports a white background. Cancellation or a provider write error may leave a partial destination; the app reports this. Device acceptance is deferred, and movie/GIF/transparent exports are not implemented in this foundation.'},
 {id:'rights',category:'account',title:'Check rights before sharing imported artwork',platform:'iOS / Android',terms:'license attribution copyright asset image audio commercial cc0',steps:['Use artwork and audio you own or have permission to use.','For provided or imported assets, retain the accompanying source and license information. Different assets may have different terms.','Check those terms for your intended use before publishing the final animation.'],note:'A plan name or paid subscription does not grant blanket commercial rights to every imported asset. This website does not issue licenses or accept private project uploads.'},
 {id:'account',category:'account',title:'Account, pricing and support availability',platform:'Website / native app',terms:'login profile username bio email password billing subscription support ticket',steps:['This website does not provide account sign-in, checkout or billing changes. Use only an available, connected account flow inside the native app.','Approved product pricing and public distribution links will need a separate release update; none are offered here.','Use the summary tool below to keep reproduction steps locally. It downloads a text file and does not submit a ticket.'],note:'Do not put passwords, payment data or entire private projects into a problem report. Authenticated support intake remains unconnected in this website source.'}
];
